# This is a basic workflow to help you get started with Actions

name: CI

inputs:
  tag:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: ${{inputs.tag}}
