# This is a basic workflow to help you get started with Actions

name: Base

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  IMAGE_NAME: "my-image-name"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Test name
        run: |
          echo 123
          echo "${{inputs.tag}}"
          echo "Test ${{env.IMAGE_NAME}}"

