# This is a basic workflow to help you get started with Actions

name: Base

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

      image:
        required: true
        type: string

jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
      - name: print
        run: |
          echo ${{inputs.image}}
          echo ${{inputs.tag}}

      - uses: docker/build-push-action@v3.2.0
        with:
          tags: ${{inputs.image}}:${{inputs.tag}}-${{github.run_id}}
