# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checkout:
    steps:
      - name: Base action
        uses: pawelkonikpl/workflows/.github/workflows/base.yml@main
        with:
          tag: "123123123"




