# This is a basic workflow to help you get started with Actions

name: Extended step

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main


environment:
  name: production
  url: https://github.com

jobs:
  checkout:
    uses: pawelkonikpl/workflows/.github/workflows/base.yml@main
    with:
      tag: "123123123"

  another-build:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Another cool step
        run: |
          echo "Test"
