# This is a basic workflow to help you get started with Actions

name: Extended step

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "test"

jobs:

  another-build:
    runs-on: ubuntu-latest
#    environment:
#      name: production
#      url: https://github.com

    steps:
      - name: Another cool step
        run: |
          echo "Test"
          echo $IMAGE_NAME

  checkout:
    needs: another-build
    uses: pawelkonikpl/workflows/.github/workflows/base.yml@main
    with:
      tag: "123123123"
