# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout:
    uses: pawelkonikpl/workflows/.github/workflows/base.yml@main
    with:
      tag: "123123123"
  
  another-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Another cool step
        run: |
          echo "Test"
