# This is a basic workflow to help you get started with Actions

name: Extended step

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "test"
  IMAGE_TAG: "123"

jobs:

  another-build:
    runs-on: ubuntu-latest
#    environment:
#      name: production
#      url: https://github.com

    steps:
      - name: Another cool step
        run: echo ${{github.run_id}}

  checkout:
    needs: another-build
    uses: pawelkonikpl/workflows/.github/workflows/base.yml@main
    with:
      tag: "test"
      image: "123"
      
  checkout1: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
        with:
          name: pawelkonikpl/guix     
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Print
        run: ls -la
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      
      - name: Install npm
        run: yarn install
        
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
  
