# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  checkout:
    uses: org/repo/.github/workflows/build.yml@main
    with:
      jdk_version: 11

    


